### ISSUE TITLE
Logo Contest

### ISSUE THREAD

**Issue by mcawley** [osmus/sotmus2020#1]
Contest for this year's logo. Winner receives a ticket to SOTMUS & 3 nights hotel.

Will need to:
1. Line up judges
2. Define parameters
3. Set timeline
4. Create announcement
5. Spread the word

**Comment by 1ec5** [comment]
While we wait for a logo, I put in a background for the website’s masthead. Doesn’t necessarily mean the logo needs to be green and prickly.

**Comment by mcawley** [comment]
2/25/20 Meeting Update:
- Kiri can encourage students to participate
- Chris can reach out to SOTM Oceania

Suggested Timeline:
- Announce contest - Monday March 2nd
- Accept entries - Two weeks or three weeks / March 2 to 15 or 22 
- Select Winner - March 17 or 24

**Comment by cbeddow** [comment]
For FOSS4G-SotM Oceania they had the community vote. Should we do that, or just judge as organizers? I can see advantages both ways.

**Comment by cbeddow** [comment]
**The design MUST**
* Include themes for Tucson or Arizona
* Be easily printable on t-shirts with as few colors as possible (no more than 5). This keeps the cost of printing down.
* Work well on different colored backgrounds (or have alternatives for light and dark backgrounds).
Be delivered in PNG file format and a scalable format (SVG or PDF).
* Not be similar to other mapping conference logos (ESRI, SOTM,FOSS4G...)
* Not communicate the brand of potential sponsors or related companies
* Not include copyrighted material that is not yours

**The design MAY**
* Come in different sizes (example: a main logo and a variant for use on small print media such as badges).

**The design should communicate**
* Local culture: indigenous, hispanic, southwest US
* OpenStreetMap theme
* Geospatial / mapping concepts
* a sense of learning and education
*  A sense of community

**The design should not communicate**
* Corporate / big business (as the sole element)
* Complexity
* Expensive
* For geeks only
* Closed community

**Comment by cbeddow** [comment]
Original Tweet from the organizers, we can model off this:

![image](https://user-images.githubusercontent.com/10554922/75380095-b91aac00-58d6-11ea-9346-6d4d5b9f2d47.png)

Link leads to their wiki: https://wiki.osgeo.org/wiki/FOSS4G_SotM_Oceania_2020/Logo_Contest

So I suggest a link to this section on our wiki: https://wiki.openstreetmap.org/wiki/State_of_the_Map_U.S._2020#Logo_Contest

Can we confirm the best way for people to submit the logo?

Could ask for:

* submit to email address (an official one?)
* submit with twitter hashtag (#sotm2020logocontest)?

**Comment by cbeddow** [comment]
I think we will submit by email only, with either an attachment or a link to the logo sent to: sotmus+logo@openstreetmap.us

**Comment by cbeddow** [comment]
### I propose this content for the wiki page:


The State of the Map US 2020 organizing committee is pleased to announce a call for logo designs. We want the community to take part in building a meaningful and memorable logo for State of the Map 2020 in Tucson, Arizona.

Entrants may be an individual or team of people, even a design company. 

## Conditions
* By submitting a logo you will be assigning your copyright to OSMUS so that it can be used across different mediums. The organizing committee may also commission improvements of the winning work as needed. 
* Entries must be submitted via email to sotmus+logo@openstreetmap.us by 11:59PM West Coast time on Sunday, 22 March 2020. The OSM US community will vote to decide which logo wins. 

## Examples
Please see past logos for some inspiration and examples:

![2019](https://2019.stateofthemap.us/assets/graphics/content/logo.png)
2019 Logo
 
![2018](https://2018.stateofthemap.us/assets/graphics/content/miotke_logo.png)
2018 Logo

![2017](https://wiki.openstreetmap.org/w/images/thumb/2/2d/State_of_the_Map_2017_U.S._Logo.svg/375px-State_of_the_Map_2017_U.S._Logo.svg.png)
2017 Logo

![2016](https://wiki.openstreetmap.org/w/images/e/e3/State_of_the_Map_US_2016_logo.png)
2016 Logo

There are several more examples on the [past event wiki pages](https://wiki.openstreetmap.org/wiki/State_Of_The_Map#State_of_the_Map_U.S._.28SotM-US.29).

## How to enter
* Create your logo in PNG file format and a scalable file format (either SVG or PDF).
* If you're not used to scalable formats please still enter the competition as we can try to help.
* Send your logo as an attachment, in a ZIP file, or included in a link to sotmus+logo@openstreetmap.us

## Logo Design Rules
**The design MUST**
* Include themes for Tucson or Arizona
* Be easily printable on t-shirts with as few colors as possible (no more than 5). This keeps the cost of printing down.
* Work well on different colored backgrounds (or have alternatives for light and dark backgrounds).
Be delivered in PNG file format and a scalable format (SVG or PDF).
* Not be similar to other mapping conference logos (ESRI, SOTM,FOSS4G...)
* Not communicate the brand of potential sponsors or related companies
* Not include copyrighted material that is not yours

**The design MAY**
* Come in different sizes (example: a main logo and a variant for use on small print media such as badges).

**The design should communicate**
* Local culture: indigenous, hispanic, southwest US
* OpenStreetMap theme
* Geospatial / mapping concepts
* a sense of learning and education
*  A sense of community

**The design should not communicate**
* Corporate / big business (as the sole element)
* Complexity
* Expensive
* For geeks only
* Closed community


## Prize
The winning entry will receive a conference registration and 3 nights hotel.

## Distribution
Logo may be included in:
* The conference website, flyers, emails, sponsor communications, t-shirts and potentially other conference swag.
* Printed material at the conference such as program of talks, notebooks, banners and conference guide. 
* Potentially small web-based button images for use on third party websites to promote the conference or fact that someone is speaking there, for placement on blogs and other web pages.

**Comment by mcawley** [comment]
Link to draft blog: https://docs.google.com/document/d/1FSeEU516AQGbFJmIBwxwUx22onGQDS-0hEq-ejJD3ng/edit?usp=sharing

**Comment by mcawley** [comment]
For the winner - if it is a team or company we can't give away that many hotel rooms... should we stick to just free entry and a tshirt or something?

**Comment by cbeddow** [comment]
@mcawley good point there, I would say that we just book a single room with free entry for all who attend, if they want to put 2-4 people in a room okay, but we can't book multiple rooms, does that work? Then it should be same cost as 1 person as for max 4?

**Comment by mcawley** [comment]
@cbeddow ended up going with: Winners will receive one free conference registration (value $200), $300 in travel reimbursement, and a limited edition 10th Anniversary t-shirt

**Comment by cbeddow** [comment]
great thinking!

**Comment by mcawley** [comment]
https://wiki.openstreetmap.org/wiki/State_of_the_Map_U.S._2020#Logo_Contest

**Comment by mcawley** [comment]
will reach out to winner with updates and re-offer ticket
